---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: Reconfigure_RAM
    inherits: 
    description: 
  fields:
  - rel2:
      value: /Integration/VCLI/Reconfigure_RAM
