---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: Reconfigure_CDROM
    inherits: 
    description: 
  fields:
  - rel2:
      value: /CompanyXYZ/Integration/VMware/RBVMOMI/UnMount_ISO
