---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: Reconfigure_VM
    inherits: 
    description: 
  fields:
  - rel1:
      value: /CompanyXYZ/Operations/StateMachines/Reconfigure/default
