---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: default
    inherits: 
    description: 
  fields:
  - openstack:
      value: openstack_best_fit
  - amazon:
      value: amazon_best_fit
