---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: default
    inherits: 
    description: 
  fields:
  - redhat:
      value: redhat_best_placement_with_scope
  - vmware:
      value: vmware_best_fit_with_scope
