---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: ReconfigVM_HotAddEnabled
    inherits: 
    description: 
  fields:
  - Step1:
      value: /Integration/VMware/vCenter/Check_PoweredOff
  - Step2:
      value: /Integration/VMware/vCenter/ReconfigVM_cpuHotAddEnabled
  - Step3:
      value: /Integration/VMware/vCenter/Check_ReconfigVM_cpuHotAddEnabled
  - Step4:
      value: /Integration/VMware/vCenter/ReconfigVM_memoryHotAddEnabled
  - step5:
      value: /Integration/VMware/vCenter/Check_ReconfigVM_memoryHotAddEnabled
