---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: VmReconfigureRequest_Created
    inherits: 
    description: 
  fields:
  - on_entry:
      value: VmReconfigureRequest_Auto_Approve
