---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: Default
    inherits: 
    description: 
  fields:
  - UnregisterFromProvider:
      value: ! '#/Cloud/VM/Retirement/StateMachines/Methods/UnregisterFromProvider'
  - DeleteFromProvider:
      value: /Cloud/VM/Retirement/StateMachines/Methods/DeleteFromProvider
  - CheckUnregisteredFromProvider:
      value: /Cloud/VM/Retirement/StateMachines/Methods/CheckUnregisteredFromProvider
  - PostDeleteFromProvider:
      value: /Integration/RedHat/OpenStack/Cinder/Delete_Openstack_Volumes
  - DeleteFromVMDB:
      value: /Cloud/VM/Retirement/StateMachines/Methods/DeleteFromVMDB
