---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: initialize_rightsizing_tags
    inherits: 
    description: 
  fields:
  - method1:
      value: initialize_rightsizing_tags
