---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: Redhat_PostProvisioon
    inherits: 
    description: 
  fields:
  - redhat_rel1:
      value: redhat_postprovisioon
